import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
// import localfont from "next/font/local";

// const monument = localfont({
// 	src: "../public/fonts/MonumentExtended-Regular.otf",
// 	weight: "400",
// });

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>{children}</body>
		</html>
	);
}
